description: 'LSTM_CNN_MERGE'
output_dir: /global/homes/a/abbatej/plasma-profile-predictor/

data:
    name: lstm_cnn
    input_filename: /global/homes/a/abbatej/small_final_data
    output_dirname: /global/cscratch1/sd/abbatej/small_data/
    preprocess: False
    sigs_0d: ['curr','pinj']
    sigs_1d: ['thomson_temp','thomson_dens']
    sigs_predict: ['temp']

    n_components: None
    avg_window: 1
    lookback: 10
    delay: 5
    train_frac: .7
    val_frac: .2

model:
    name: lstm_cnn_merge
    rho_length_out: 65

    include_cnn: False
    cnn_activation: 'linear'
    cnn_padding: 'same'
    kernel_size: 10
    max_pool_size: 2
    num_filters: 2
    dense_cnn_size: 10
    dense_cnn_activation: 'relu'
    num_dense_cnn_layers: 0

    dense_pre_size: 20
    dense_pre_activation: 'relu'
    num_pre_layers: 2
    rnn_type: 'LSTM'
    rnn_size: 40
    rnn_activation: 'relu'
    num_final_layers: 0
    dense_final_activation: 'relu'
    dense_final_size: 40

optimizer:
    name: Adam
    lr: 0.001

training:
    batch_size: 128
    n_epochs: 50
    loss: 'mean_squared_error'
    metrics: [mae]
