description: 'LSTM_CNN_MERGE'
output_dir: $HOME/plasma_profiles_predictor/

data:
    name: lstm_cnn
    input_dir_name: '/global/homes/a/abbatej/'
    preprocess: True
    sigs_0d: ['curr_target','pinj', 'ech']
    sigs_1d: ['e_temp']
    sigs_predict: ['e_temp']

    n_components: 2
    avg_window: 10
    lookback: 4
    delay: 2
    train_frac: .7
    val_frac: .2

model:
    name: lstm_cnn_merge
    rho_length_out: 30

    include_cnn: False
    cnn_activation: 'linear'
    cnn_padding: 'same'
    kernel_size: 10
    max_pool_size: 2
    num_filters: 2
    dense_cnn_size: 10
    dense_cnn_activation: 'relu'
    num_dense_cnn_layers: 0

    dense_pre_size: 20
    dense_pre_activation: 'relu'
    num_pre_layers: 2
    rnn_type: 'LSTM'
    rnn_size: 40
    rnn_activation: 'relu'
    num_final_layers: 0
    dense_final_activation: 'relu'
    dense_final_size: 40

optimizer:
    name: Adam
    lr: 0.001

training:
    batch_size: 128
    n_epochs: 60
    loss: 'mean_squared_error'
    metrics: [mae]
