description: 'RNN'
output_dir: $SCRATCH/sc18-dl-tutorial/rnn-N${SLURM_JOB_NUM_NODES}-${SLURM_JOB_ID}

data:
    name: rnn
    input_data_file: '/global/homes/a/abbatej/profile_predictor/input_data/train_data'
    num_sigs: 3

model:
    name: rnn
    input_shape: 41
    output_shape: 38

optimizer:
    name: Adam
    lr: 0.001

training:
    batch_size: 128
    n_epochs: 20
    steps_per_epoch: 128 #should ultimately be the number of train samples
    loss: mse
    metrics: [mae]
