description: 'TREND_PLUS_ACTUATORS'
output_dir: Users/jabbate/plasma-profile-predictor/

data:
    name: trend_plus_actuators
    input_filename: /Users/jabbate/data/final_data_medium
    output_dirname: /Users/jabbate/data/

    train_frac: .7
    val_frac: .2

    stride: 2
    preprocess: True

data_and_model:
    sigs_0d: ['curr','pinj','gasA']
    sigs_1d: ['thomson_temp', 'thomson_dens','press']
    sigs_predict: ['temp']
    lookbacks: 
        curr: 10
        pinj: 10
        gasA: 10
        ech: 10
        thomson_temp: 0
        thomson_dens: 0
        temp: 0
        dens: 0
        press: 0
        ffprime: 0
    delay: 4

model:
    name: dif_lookbacks
    rho_length_out: 33

    dense_0d_size: 10
    dense_0d_activation: 'relu'

    rnn_type: 'LSTM'
    rnn_size: 10
    rnn_activation: 'relu'
    num_rnn_layers: 5

    num_final_layers: 5
    dense_final_size: 10
    dense_final_activation: 'relu'

optimizer:
    name: Adam
    lr: 0.001

training:
    batch_size: 256
    n_epochs: 50
    loss: 'mean_squared_error'
    metrics: [mae]
